@Test_API_HostAddress = http://localhost:5153

GET {{Test_API_HostAddress}}/weatherforecast/
Accept: application/json

# ###

POST {{Test_API_HostAddress}}/weatherforecast/
Accept: application/json

{
  sumary = "works"
}

###

PUT {{Test_API_HostAddress}}/weatherforecast/
Accept: application/json
Body :{ id = 0,sumary = "works"}
###

DELETE {{Test_API_HostAddress}}/weatherforecast/1
Accept: application/json

###

GET {{Test_API_HostAddress}}/Subject/
Accept: application/json

###


POST {{Test_API_HostAddress}}/Subject/
Content-Type: application/json
Accept: application/json

"MaterialScience"

###

PUT {{Test_API_HostAddress}}/Subject?id=1
Content-Type: application/json
Accept: application/json
"Science-1"
###

DELETE {{Test_API_HostAddress}}/Subject?id=1

Accept: application/json
